from data.secret import get_secret

secret = get_secret()
SLACK_COLLECTOR_BOT_TOKEN = secret['SLACK_COLLECTOR_BOT_TOKEN']
AIR_TABLE_APP_NAME = secret['AIR_TABLE_APP_NAME']
AIR_TABLE_API_KEY = secret['AIR_TABLE_API_KEY']
LABEL_STUDIO_ACCESS_TOKEN = secret['LABEL_STUDIO_ACCESS_TOKEN']
LABEL_STUDIO_URL = secret['LABEL_STUDIO_URL']
