nli:
  _target_: prompt_tuning.dataset.PromptNliDataModule
  seed: 42
  dataset_path: klue
  dataset_name: nli
  test_rate: 0.1
  shuffle: False


labeled:
  _target_: prompt_tuning.dataset.PromptLabeledDataModule
  seed: 42
  dataset_path: ${oc.env:PROJECT_ROOT}/static/labeled_dataset.csv
  test_rate: 0.15
  shuffle: False


loader:
  _target_: prompt_tuning.dataset.PromptLoader
  max_seq_length: 256
  decoder_max_length: 3
  batch_size: 4
  teacher_forcing: False
  predict_eos_token: False
  truncate_method: head
