train:
  _target_: prompt_tuning.dataset.PromptLabeledDataModule
  seed: 42
  dataset_path: ${oc.env:PROJECT_ROOT}/static/train.csv
  shuffle: False
  use_back_translation_augmentation: True


test:
  _target_: prompt_tuning.dataset.PromptLabeledDataModule
  seed: 42
  dataset_path: ${oc.env:PROJECT_ROOT}/static/test.csv
  shuffle: False


loader:
  _target_: prompt_tuning.dataset.PromptLoader
  max_seq_length: 256
  decoder_max_length: 3
  batch_size: 4
  teacher_forcing: False
  predict_eos_token: False
  truncate_method: head
