_target_: prompt_tuning.dataset.PromptDataModule
seed: 42
dataset_path: klue
dataset_name: nli
split_rate: [8, 1, 1]
max_seq_length: 256
decoder_max_length: 3
batch_size: 4
teacher_forcing: False
predict_eos_token: False
truncate_method: head
