root_dir: ${oc.env:PROJECT_ROOT}

data_dir: ${paths.root_dir}/static/

ckpt_dir: ${paths.root_dir}/ckpt/

pretrain_model_path: ${paths.root_dir}/prompt_tuning/outputs/2022-09-18/18-10-05/best_model.pt
